spring:
  ai:
    azure:
      openai:
        api-key: ${AZURE_API_KEY}
        endpoint: ${AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            model: ${AZURE_OPENAI_DEPLOYMENT_NAME}
            temperature: 0.7
            max-tokens: 2000
            
azure:
  ai:
    endpoint: ${AZURE_AI_ENDPOINT}
      
server:
  port: 8080
